<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX08yWcz\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX08yWcz/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerX08yWcz.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerX08yWcz\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerX08yWcz\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'X08yWcz',
    'container.build_id' => 'fb5cadba',
    'container.build_time' => 1543445616,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerX08yWcz');
